version: '3.9'


services:

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432


    container_name: db

    volumes:
      - ./data:/var/lib/postgresql/data



  app:
    build: .
    env_file:
      - .env

    ports:
      - 8000:8000


    depends_on:
      - db
    
