"""empty message

Revision ID: f2041508d107
Revises: 
Create Date: 2024-03-27 19:05:25.051759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2041508d107'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('third_name', sa.String(), nullable=False),
    sa.Column('passport_data', sa.String(length=11), nullable=False),
    sa.Column('date_to_birth', sa.Date(), nullable=False),
    sa.Column('date_passport', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('man', 'women', name='sexenumss'), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('passport_data')
    )
    op.create_table('url_update_passowrd',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_update_passowrd')
    op.drop_table('user_table')
    # ### end Alembic commands ###
